version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"

  node-app:
    build: .
    ports:
      - "4366:7000"
    environment:
      PORT: 7000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app